-- Insert demo connectors
INSERT INTO public.connectors (id, name, platform, status, last_sync, sync_frequency, error_count, total_flows, monthly_executions, avg_response_time, api_usage_used, api_usage_limit, api_usage_reset_date, organization_id) VALUES
('zapier-demo', 'Zapier', 'zapier', 'connected', NOW() - INTERVAL '1 hour', 'realtime', 2, 15, 4500, 1.2, 3500, 10000, '2025-08-01T00:00:00Z', (SELECT id FROM organizations LIMIT 1)),
('make-demo', 'Make', 'make', 'connected', NOW() - INTERVAL '2 hours', 'hourly', 0, 8, 2100, 0.8, 1200, 5000, '2025-08-01T00:00:00Z', (SELECT id FROM organizations LIMIT 1)),
('hubspot-demo', 'HubSpot', 'hubspot', 'disconnected', NULL, 'daily', 15, 12, 850, 3.5, 0, 2500, '2025-08-01T00:00:00Z', (SELECT id FROM organizations LIMIT 1)),
('salesforce-demo', 'Salesforce', 'salesforce', 'error', NOW() - INTERVAL '1 day', 'daily', 8, 20, 3245, 2.1, 12000, 15000, '2025-08-01T00:00:00Z', (SELECT id FROM organizations LIMIT 1))
ON CONFLICT (id) DO NOTHING;

-- Insert demo flows
INSERT INTO public.flows (
  id, name, external_id, tool, summary, description, duplicate_of, orphan, status, 
  trigger_type, trigger_config, actions, frequency, last_run, next_run, 
  success_rate, avg_execution_time, total_executions, monthly_executions,
  monthly_cost, cost_per_execution, error_count, warning_count, avg_response_time,
  owner_id, department, business_value, organization_id, connector_id
) VALUES
(
  'flow-deal-won-slack', 
  'Deal Won → Slack Notification', 
  'zapier-deal-won-001',
  'zapier',
  'Send Slack notification when deal is won in HubSpot',
  'Automatically notify the sales team when a deal reaches won status',
  NULL,
  false,
  'active',
  'webhook',
  '{"source": "hubspot", "event": "deal.updated"}',
  '[{"id": "a1", "type": "slack_message", "config": {"channel": "#sales", "message": "🎉 New deal won: {{deal.name}} - ${{deal.amount}}"}}]',
  'realtime',
  NOW() - INTERVAL '2 hours',
  NULL,
  98.5,
  2.1,
  1250,
  85,
  12.50,
  0.15,
  8,
  3,
  1.8,
  'Sales Manager',
  'sales',
  'high',
  (SELECT id FROM organizations LIMIT 1),
  'zapier-demo'
),
(
  'flow-duplicate-deal', 
  'Deal Won → Slack Alert (Duplicate)', 
  'make-deal-won-002',
  'make',
  'Duplicate of Deal Won notification created in Make platform',
  'Duplicate flow created in Make that does similar functionality',
  'flow-deal-won-slack',
  false,
  'active',
  'webhook',
  '{"source": "hubspot", "event": "deal.updated"}',
  '[{"id": "a2", "type": "slack_message", "config": {"channel": "#general", "message": "Deal won: {{deal.name}}"}}]',
  'realtime',
  NOW() - INTERVAL '1 hour',
  NULL,
  92.1,
  3.5,
  890,
  78,
  15.60,
  0.20,
  15,
  8,
  2.9,
  'Marketing Specialist',
  'sales',
  'medium',
  (SELECT id FROM organizations LIMIT 1),
  'make-demo'
),
(
  'flow-contact-archive', 
  'Midnight Contact Archive', 
  'hubspot-archive-001',
  'hubspot',
  'Archive stale contacts that haven\'t been active in 6+ months',
  'Automatically archive contacts with no recent activity to keep database clean',
  NULL,
  true,
  'disabled',
  'schedule',
  '{"cron": "0 0 * * *"}',
  '[{"id": "a3", "type": "contact_update", "config": {"property": "lifecycle_stage", "value": "archived"}}]',
  'daily',
  '2025-06-15T00:00:00Z',
  NULL,
  45.2,
  120.5,
  35,
  2,
  8.00,
  4.00,
  25,
  12,
  95.2,
  'Data Analyst',
  'marketing',
  'low',
  (SELECT id FROM organizations LIMIT 1),
  'hubspot-demo'
),
(
  'flow-lead-scoring', 
  'Lead Scoring & Routing', 
  'zapier-lead-score-001',
  'zapier',
  'Score new leads and route to appropriate sales rep',
  'Automatically score incoming leads and assign to sales reps based on criteria',
  NULL,
  false,
  'active',
  'event',
  '{"object": "contact", "event": "created"}',
  '[{"id": "a4", "type": "score_calculation", "config": {"criteria": ["company_size", "industry", "role"]}}, {"id": "a5", "type": "lead_assignment", "config": {"routing_logic": "round_robin"}}]',
  'realtime',
  NOW() - INTERVAL '30 minutes',
  NULL,
  94.8,
  5.2,
  2100,
  180,
  25.00,
  0.14,
  12,
  5,
  4.1,
  'Sales Operations',
  'marketing',
  'high',
  (SELECT id FROM organizations LIMIT 1),
  'zapier-demo'
)
ON CONFLICT (id) DO NOTHING;

-- Insert demo execution logs
INSERT INTO public.execution_logs (flow_id, status, start_time, end_time, duration, data_processed, cost, error_message, external_execution_id) VALUES
('flow-deal-won-slack', 'success', NOW() - INTERVAL '2 hours', NOW() - INTERVAL '2 hours' + INTERVAL '2.1 seconds', 2100, 1, 0.15, NULL, 'exec-001'),
('flow-duplicate-deal', 'failure', NOW() - INTERVAL '1 hour', NOW() - INTERVAL '1 hour' + INTERVAL '5 seconds', 5000, 0, 0.20, 'Slack API rate limit exceeded', 'exec-002'),
('flow-lead-scoring', 'success', NOW() - INTERVAL '30 minutes', NOW() - INTERVAL '30 minutes' + INTERVAL '5.2 seconds', 5200, 1, 0.14, NULL, 'exec-003'),
('flow-deal-won-slack', 'success', NOW() - INTERVAL '3 hours', NOW() - INTERVAL '3 hours' + INTERVAL '1.8 seconds', 1800, 1, 0.15, NULL, 'exec-004'),
('flow-lead-scoring', 'success', NOW() - INTERVAL '1 hour', NOW() - INTERVAL '1 hour' + INTERVAL '4.5 seconds', 4500, 1, 0.14, NULL, 'exec-005')
ON CONFLICT (id) DO NOTHING;