// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nzorvmqbqrfftonufqsp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56b3J2bXFicXJmZnRvbnVmcXNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwOTI1ODksImV4cCI6MjA2ODY2ODU4OX0.nXFvq9BjcLwHIEpMNOYEciPINd5DYnffsDVPsFPAiqQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});